<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ProductList.aspx.cs" Inherits="Acme_Motors.ProductList" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <section>
        <div>
            <hgroup>
                <h2>
                    <%: Page.Title %>
                </h2>
            </hgroup>
            <asp:HyperLink NavigateUrl="~/AddProduct.aspx" Text="Add new Vehicle" runat="server">
                <p>Add new:</p>                           
            </asp:HyperLink>
            <br />
        <asp:Label Text="show:" runat="server"/>            
        <asp:DropDownList AutoPostBack="true" ID="DiplayCar" runat="server">
                <asp:ListItem Text="All" Value="" />
                <asp:ListItem Text="Car"/>
                <asp:ListItem Text="Motorbike"/>
                <asp:ListItem Text="Truck"/>
                <asp:ListItem Text="Engine"/>
                <asp:ListItem Text="Manufacturer"/>                
        </asp:DropDownList>
            <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
            <br />
            <br />
            <asp:GridView runat="server" ID="productsGrid"
                ItemType="Acme_Motors.Models.Product" DataKeyNames="ProductID"
                SelectMethod="GetProducts"
                UpdateMethod="productsGrid_UpdateItem"
                DeleteMethod="productsGrid_DeleteItem"
                AllowSorting="true" AllowPaging="true" PageSize="10"
                AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
            </asp:GridView>
            <br />
            <br />
            <asp:ListView ID="producList" runat="server"
                DataKeyNames="ProductID" GroupItemCount="5"
                ItemType="Acme_Motors.Models.Product" SelectMethod="GetProducts">
                <EmptyDataTemplate>
                    <table>
                        <tr>
                            <td>No data was returned.</td>
                        </tr>
                    </table>
                </EmptyDataTemplate>
                
                <EmptyItemTemplate>
                    <td />                                    
                </EmptyItemTemplate>
                <GroupTemplate>
                    <tr id="itemPlaceHolderContainer" runat="server">
                        <td id="itemPlaceHolder" runat="server"></td>
                    </tr>
                </GroupTemplate>
                <ItemTemplate>
                    <td runat="server">
                        <table>
                            <tr>
                                <td>
                                    <a href="ProductDetails.aspx?productID=<%#:Item.ProductID %>">
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <a href="ProductDetails.aspx?productID=<%#:Item.ProductID %>">
                                        <span>
                                            <%#:Item.ProductName %>
                                        </span>
                                    </a>
                                    <br />
                                    <span>
                                        <b>Price :</b><%#:String.Format("{0:c}", Item.UnitPrice) %>
                                    </span>
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                            </tr>
                        </table>
                        </p>
                    </td>
                </ItemTemplate>
                <LayoutTemplate>
                    <table style="width:100%;">
                        <tbody>
                            <tr>
                                <td>
                                    <table id="groupPlaceHolderContainer" runat="server" style="width:100%;">
                                        <tr id="groupPlaceHolder"></tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </LayoutTemplate>
            </asp:ListView>
        </div>        
    </section>
</asp:Content>
